### PR TITLE
Add support for creating a lock file from a meta.yaml

### LINKED ISSUE #31: Allow creating a lockfile from a meta.yaml

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Added support for creating a lockfile by pointing at a meta.yaml file.

This uses a minimal meta.yaml parser that is platform aware (but nothing else) to generate the requirements

Resolves #31

### CODE REVIEW

**Comment by ocefpaf** [comment]
LGTM. Maybe @marcelotrevisani have some advice on the meta.yaml parsing b/c I know he has been working on that for a while.

**Comment by marcelotrevisani** [comment]
I am using ruamel instead of pyyaml because ``pyyaml`` does not handle well comments and it does not support much configurations.
One thing which I am thinking to do is to extract the code responsible to handle the recipe from grayskull to a separated project, and there we can be very specific to parse conda`s recipes

**Comment by scopatz** [comment]
A brief look and things look good!  I don't think comments much matter here.  Conda-lock won't ever try to write the YAML back out.  The only place I  can see it being an issue is when selectors are behind comments

**Comment by ocefpaf** [comment]
@mariusvniekerk, new release?

**Comment by mariusvniekerk** [comment]
Yeah a new release sounds good 0.4.0

**Pull request merged**
